# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communeapp', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='hood',
        ),
    ]
