# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communeapp', '0007_remove_message_hood'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communeapp.Neighbourhood'),
            preserve_default=False,
        ),
    ]
