# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communeapp', '0008_message_hood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
