# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communeapp', '0009_business_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
